BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ASIGNATURA" (
	"ID"	INTEGER NOT NULL,
	"NOMBRE"	TEXT,
	"ID_PROFESOR"	INTEGER,
	PRIMARY KEY("ID"),
	UNIQUE("ID_PROFESOR")
);
CREATE TABLE IF NOT EXISTS "TAREA" (
	"ID"	INTEGER NOT NULL,
	"NOMBRE"	TEXT,
	"FECHA_FIN"	TEXT,
	"CALIFICACION"	INTEGER,
	"ID_ASIGNATURA"	INTEGER,
	"ID_ALUMNO"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ID_ASIGNATURA") REFERENCES "ASIGNATURA"("ID"),
	FOREIGN KEY("ID_ALUMNO") REFERENCES "ALUMNO"
);
CREATE TABLE IF NOT EXISTS "ESTUDIA" (
	"ID_ALUMNO"	INTEGER,
	"ID_ASIGNATURA"	INTEGER,
	PRIMARY KEY("ID_ALUMNO","ID_ASIGNATURA"),
	FOREIGN KEY("ID_ASIGNATURA") REFERENCES "PROFESOR"("ID"),
	FOREIGN KEY("ID_ALUMNO") REFERENCES "ALUMNO"("ID")
);
CREATE TABLE IF NOT EXISTS "PROFESOR" (
	"ID"	INTEGER NOT NULL,
	"NOMBRE"	TEXT,
	"APELLIDO"	TEXT,
	"CONTRASEÑA"	TEXT NOT NULL,
	"DIRECCION"	TEXT,
	"EDAD"	INTEGER,
	"EMAIL"	TEXT,
	"SALARIO"	INTEGER,
	"NOMBRE_USUARIO"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ALUMNO" (
	"ID"	INTEGER NOT NULL,
	"NOMBRE"	TEXT,
	"APELLIDO"	TEXT,
	"CONTRASEÑA"	TEXT NOT NULL,
	"DIRECCION"	TEXT,
	"EDAD"	INTEGER,
	"EMAIL"	TEXT,
	"CURSO"	INTEGER,
	"NOMBRE_USUARIO"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
